version: '3.8'

services:
  # The PostgreSQL Database service
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env # for POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB
    ports:
      - "5432:5432"

  # The Redis service for Celery's message broker
  redis:
    image: "redis:6-alpine"
    restart: always
    ports:
      - "6379:6379"

  # The Flask web application service
  web:
    build: .
    # The command to start the Flask development server
    command: python run.py
    volumes:
      # Mount the current directory into the container for live code reloading
      - .:/app
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - redis
      - db

  # The Celery worker service
  worker:
    build: .
    command: celery -A celery_worker.celery worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
